version: "3.8"
services:
  postgres:
    image: ivanipani1/postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: remy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dabahdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U remy -d dabahdb"]
      interval: 3s
      timeout: 5s
      retries: 5

  dev: &dev
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GITHUB_USER:
        GITHUB_TOKEN:
    command: sleep infinity
    volumes:
      - .:/workarea
    depends_on:
      postgres:
        condition: service_healthy

  test:
    << : *dev
    depends_on:
      postgres:
        condition: service_healthy