[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dabah.service.utils"
description = "Common setup, configuration logic for Python services"
authors = [
    {name = "Ivan Perdomo", email = "iperdomo2016@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version", "dependencies"]

[tool.setuptools_scm]
version_file = "_version.py"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
include = ["dabah.service.utils"]

[tool.pytest.ini_options]
log_cli = 1
log_cli_level = "DEBUG"