[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "dabah.service.utils"
description = "Common setup, configuration logic for Python services"
dynamic = ["version", "dependencies"]

[tool.setuptools_scm]
version_file = "_version.py"

[tool.setuptools.packages.find]
where = ["./dabah/"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
